### ISSUE TITLE
python 2 dependency

### ISSUE THREAD

**Issue by cbendele** [TUD-OS/NUL#1]
On more and more modern linux systems [/usr/bin/]python is a symlink to python3 and not to python2. Python 3, however, is not backward compatible and many of the python 2 scripts in the NUL tree fail when run with python 3.

A possible fix would be to replace the line
# !/usr/bin/env python

with
# !/usr/bin/env python2

on top of each and every python script in the tree.
running
find . -name "*.py" -print | xargs sed -i 's/env python /env python2 /g'
in the tld should do this.

**Comment by blitz** [comment]
Sorry, missed this issue. You are of course correct. I'll fix this.

**Comment by blitz** [comment]
Fix is in the pipeline. Will be pushed in about 24h after the nightly tests.

**Comment by blitz** [comment]
Turn out our test box is Debian and it will only have a /usr/bin/python2 symlink in the next stable release. What distro has /usr/bin/python pointing to python 3?

**Comment by wentasah** [comment]
On Tue, Sep 18 2012, Julian Stecklina wrote:

> Turn out our test box is Debian and it will only have a
> /usr/bin/python2 symlink in the next stable release. What distro has
> /usr/bin/python pointing to python 3?

For now I created python2 symlink on the test box and rerun the tests.
However I'd appreciate to change python2 to something like python2.7,
which would work even in today's Debian systems (such as my laptop :-)

Cheers,
-Michal

**Comment by wentasah** [comment]
On Tue, Sep 18 2012, Michal Sojka wrote:

> However I'd appreciate to change python2 to something like python2.7,
> which would work even in today's Debian systems (such as my laptop :-)

Forget this. python2.7 is not on our test box as well. There is only
python2.6. So having python2 is probably a good solution. I only have to
wait for our admin to create python2 symlink in /usr because scons
ignores custom PATH settings.

-Michal
