### ISSUE TITLE
scons ignore env variables

### ISSUE THREAD

**Issue by parthy** [TUD-OS/NUL#10]
When having a setup with certain proxy settings stored in environment variables for git, scons fails to pass them through.

**Comment by blitz** [comment]
That is actually a design feature of scons. To quote the manual:

> Unlike Make, SCons does not automatically copy or import values between different environments [...]. This is a deliberate
> design choice to make sure that builds are, by default, repeatable regardless of the values in the user's external environment. 
> This avoids a whole class of problems with builds where a developer's local build works because a custom variable setting 
> causes a different compiler or build option to be used, but the checked-in change breaks the official build because it uses 
> different environment variable settings.

I'll take care of it.

**Comment by blitz** [comment]
@parthy, can you check whether the patch works for you?

**Comment by parthy** [comment]
I think the important env var for this is GIT_PROXY_COMMAND, since as NOVA_URL a git:// protocol one is used. Can you include that var before I test? ;)

**Comment by blitz** [comment]
HTH
