### ISSUE TITLE
64bit binary available?

### ISSUE THREAD

**Issue by fbq** [TUD-OS/NUL#12]
Hi there,

  I want to run NUL on my desktop, with coreduo2 E7500 cpu, which support 64bit OS. I want to test a 64bit guest OS on NUL, so which first came into my mind is compile ALL to 64bit binary.

  NOVA, the hypervisor, can be compiled to 64bit binary, but I didn't find a way to compile NUL to 64bit, the SConscript in NUL/base/ specifies the 32bit target in a hard code way.
`target_env['CCFLAGS'] = '-m32 '`
  After I changed the SConscript to -m64, a lot of compile errors occurred.

  If I use 64bit hypervisor to run 32bit userland, the elf header check will not pass, so the execution context will die.
  So, I wonder whether it is possible for me to compile a 64bit userland now? Or, maybe I should modified the code of NOVA to support 32bit userland in 64bit hypervisor.

Thanks

**Comment by alex-ab** [comment]
There is no 64bit support for NUL and there are (to my knowledge) no plans to extend NUL. If you're interested in a 64bit userland for the NOVA kernel you can use Genode or NRE.

**Comment by fbq** [comment]
Thanks, I will try NRE.
