### ISSUE TITLE
UTCB data block size hardcoded (EXCEPTION_WORDS)

### ISSUE THREAD

**Issue by parthy** [TUD-OS/NUL#13]
With the most recent NOVA kernel, NUL doesn't work anymore. The UTCB layout changed, thus the number of exception words changed as well. Beside the fact that the enum is defined at the very bottom, far separated from the UTCB definition, it is generally a bad thing to hardcode this number. As soon as the UTCB layout is extended, NUL will break. Maybe one should consider doing this dynamically.

**Comment by udosteinberg** [comment]
NUL could do something similar to what the NOVA microhypervisor is doing - wrap the whole UTCB data area in a struct and then compare the number of untyped items against sizeof (Utcb_data) / sizeof (mword).
