### ISSUE TITLE
host82573 driver is terribly slow with 82579LM network interface

### ISSUE THREAD

**Issue by tfc** [TUD-OS/NUL#17]
Hi there,

One of the NUL machines here is equipped with a DQ67SW mainboard, which provides an 82579LM network interface.

The problem is that it generally works, but i cannot get it transfer data faster than ~10 Mbits/sec. Does someone else have experience with NUL using this network interface?

**Comment by blitz** [comment]
Is this still an issue? Might be a failure to properly autonegotiate.

**Comment by tfc** [comment]
Well, we've got an internal patch for that now. With this patch, it works really great.
Don't know if/when it will be possible to send the changes back to the NUL project.

However, there was some bit banging on registers which are documented as "reserved" to make the NIC slow. They do it the same way in the Linux kernel...

**Comment by blitz** [comment]
I've seen this code, so I'll just mark this bug as WONTFIX. ;-)
