### ISSUE TITLE
Upgrade to interface version 6

### ISSUE THREAD

**Issue by udosteinberg** [TUD-OS/NUL#18]
NUL doesn't work with the most recent version of the NOVA microhypervisor.

The following would need to be changed:
- base/apps/sigma0/linker.ld - update `__nova_api_version` from 5 to 6
- base/include/sys/syscalls.h - add `NOVA_PT_CTRL`
- portals whose handlers expect the capability selector in EAX (RDI) need to be configured using the new `pt_ctrl` hypercall to set the expected selector value.

**Comment by alex-ab** [comment]
Please have a look whether you can live with the patch, @blitz, @udosteinberg.

**Comment by udosteinberg** [comment]
That looks like the minimally invasive way to set a portal identifier for each portal and I wouldn't object to it.

However, not all portal functions make use of the identifier and some may even benefit from setting a custom value rather than computing it from the selector. So from a future-friendly perspective it may make sense to
- add a new `pid` parameter to `nova_create_pt` and have that parameter default to `idx_pt`. That will allow callers to set a custom identifier in the future. That's the only thing I would change in your current patch.
- functions that want to set a custom portal identifier can just do so by passing their desired `pid` to `nova_create_pt` and we can set the default parameter to 0 at any time to see what pieces of code break.
- once everything works with the default parameter being 0, we can remove `nova_ctl_pt` from `nova_create_pt` again and move it into the callers that previously set the `pid` parameter.

This can be done incrementally. For now the first bullet point would be sufficient, I guess.

**Comment by blitz** [comment]
@alex-ab , looks good. A minor bit of nit picking: Shouldn't `nova_create_pt` unmap the portal, if nova_ctl_pt failed?

**Comment by alex-ab** [comment]
@blitz, @udosteinberg : thx for the comments, please have a look again

**Comment by blitz** [comment]
Looks non-intrusive enough. :)
