### ISSUE TITLE
Direct I/O port assignment to VM not working

### ISSUE THREAD

**Issue by udosteinberg** [TUD-OS/NUL#2]
The purpose of the "dio" parameter is to give a VM direct access to an I/O port. This is currently not working. One reason is that the hypervisor now honors the G-bit for I/O ports as well. That is, if G=0, the I/O port will be added to the bitmap of the VMM only. If G=1, the I/O port will additionally be added to the bitmap of the VM.

But even prior to the hypervisor change, booting a VM with "dio:0x80+0x1 nullio:0x80" doesn't seem to work and instead kills the VMM.

**Comment by udosteinberg** [comment]
Looks like base/apps/sigma0/sigma0.cc:1075 should have DESC_IO_ALL instead of DESC_CAP_ALL at the end of the line in order to delegate the I/O capabilities from Sigma0 to the VMM.

With that change, the VMM has access to the I/O port and is executing IN/OUT on behalf of the vCPU. I'm not sure if that's intended or whether "dio" is supposed to give the guest direct access to the port, without causing a VM exit. In the latter case, the mapping in sigma0.cc:1075 would also have to set the G-bit.

**Comment by blitz** [comment]
I'll have a look at this, when I am back in my office (Oct 1st).

**Comment by alex-ab** [comment]
I fixed at least the obvious part (using DESC_IO_ALL). The fun I let to you @blitz  ;-)

**Comment by blitz** [comment]
Meh. :-)

**Comment by vmmon** [comment]
> With that change, the VMM has access to the I/O port and is executing IN/OUT on behalf of the vCPU. I'm not sure if that's intended or whether "dio" is supposed to give the guest direct access to the port, without causing a VM exit. 

That was intendend,  as proxying the IN/OUT in the VMM  leads to the same results independently whether the VCPU is running in the VM or in the emulator, especially if
-  the guest changed the I/O bars of directly assigned PCI devices, or
- I/O regions  overlap.

While one can detect these cases and switch between proxying and direct access dynamically,  it surely complicates the code a lot.

I would therefore keep it the way it is now and implement the optimization only if there is a scenario which really requires the fastest I/O  port access for the guest.

**Comment by blitz** [comment]
So unless someone comes up with a device where I/O port accesses are a bottleneck, I guess we can close this bug.
