### ISSUE TITLE
VESA mode info structure broken

### ISSUE THREAD

**Issue by parthy** [TUD-OS/NUL#3]
By accident I stumbled a problem with the VESA mode info structure. The structure seems to be correct until here:

https://github.com/TUD-OS/NUL/blob/master/base/include/host/vesa.h#L55

But then the field bank_size is omitted, instead the vbe1 field contains more elements to compensate. This is no problem when using the structure in a whole (like sigma0 does when supplying Vancouver with the available modes), but when accessing the fields selectively, bad things can happen.

I think this is not a critical issue, but still an unnecessary cosmetic problem.

**Comment by blitz** [comment]
Thanks Alex. :)
