### ISSUE TITLE
Compilation failure with gcc 4.6.3.

### ISSUE THREAD

**Issue by blitz** [TUD-OS/NUL#4]
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3.

scons: Reading SConscript files ...
Installing into /srv/tftp. Use scons tftp=/foo to change this.
scons: done reading SConscript files.
scons: Building targets ...
        CXX apps/admission/main.o
In file included from
/home/apxen/dev/nova-userland-0.4/base/include/sigma0/sigma0.h:22:0,
                 from
/home/apxen/dev/nova-userland-0.4/passive/apps/admission/main.cc:18:
/home/apxen/dev/nova-userland-0.4/base/include/nul/message.h: In
constructor 'MessageHostOp::MessageHostOp(MessageHostOp::Type, long
unsigned int, long unsigned int, unsigned int)':
/home/apxen/dev/nova-userland-0.4/base/include/nul/message.h:529:12:
error: initializations for multiple members of
'MessageHostOp::<anonymous union>'
scons: **\* [apps/admission/main.o] Error 1
scons: building terminated because of errors.

**Comment by alex-ab** [comment]
Already fixed in master branch with commit 63d027106ad36d109dbdd8fb27acb54f0f597a1a

**Comment by blitz** [comment]
Oops. My email delay was too long...
