### ISSUE TITLE
AHCI problem

### ISSUE THREAD

**Issue by sammmy** [TUD-OS/NUL#5]
I have a problem with virtual AHCI controller. As a result of providing hostdriver for AHCI controller and attaching an AHCI controller to a PCI bus in the VM, I can see the virtual AHCI controller in my VM but I can't initialize a hard drive. What's my fault?

Configuration:
    menu.lst
        title NOVA
        kernel /apps/hypervisor serial spinner iommu
        module /apps/sigma0.nul tracebuffer_verbose S0_DEFAULT hostvga hostvesa hostserial:,,4 hostide:2 hostahci service_disk          service_config script_start:1,1 script_waitchild verbose hostkeyb:0,0x60,1,12,2
        module /apps/vancouver.nul
        module /apps/hypervisor
        module /apps/sigma0.nul
        module /cfg/vancuver.nulconfig
        module /munich
        module /vmlinuz-3.4.4
        module /initrd.gz
        module /cfg/vmlinux.nulconfig

```
/cfg/vancuver.nulconfig
    sigma0::mem:64 sigma0::dma name::/s0/log name::/s0/timer name::/s0/fs/rom name::/s0/admission name::/s0/disk ||
    rom://apps/vancouver.nul PC_PS2 || 
    rom://apps/hypervisor spinner ||
    rom://apps/sigma0.nul S0_DEFAULT hostvga:0,0 hostkeyb hostserial:,,4, ||

/cfg/vmlinux.nulconfig
    sigma0::mem:64 sigma0::dma name::/s0/log name::/s0/timer name::/s0/fs/rom name::/s0/admission name::/s0/disk ||
    rom://apps/vancouver.nul PC_PS2 ahci drive:0,0,0 || 
    rom://munich ||
    rom://vmlinuz-3.4.4 clocksource=tsc root=/dev/ram0 ||
    rom://initrd.gz
    sigma0::mem:64 sigma0::dma name::/s0/log name::/s0/timer name::/s0/fs/rom name::/s0/admission name::/s0/disk sigma0::drive:0 ||
```

Boot log:

   NOVA Microhypervisor v5-5f7e435 (x86_32): Sep 25 2012 22:12:22 [gcc 4.5.1]

[ 0] CORE:0:0:0 6:2a:3:4 [8]                Genuine Intel(R) CPU 0 @ 1.40GHz
[ 2] CORE:0:0:1 6:2a:3:4 [8]                Genuine Intel(R) CPU 0 @ 1.40GHz
[ 1] CORE:0:1:0 6:2a:3:4 [8]                Genuine Intel(R) CPU 0 @ 1.40GHz
[ 3] CORE:0:1:1 6:2a:3:4 [8]                Genuine Intel(R) CPU 0 @ 1.40GHz
    => hostide:2 <=
DISK controller #1 IDE at 300
    => hostahci <=
MSI 7b enabled for bdf fa MSI fee00018/7b
DISK controller #1 AHCI fa id 1c038086 mmio f7f26000
AHCI: cap e730ff45 cap2 4 global 80000000 ports 0 version 10300 bohc 0
    => service_disk <=
Constructing service /disk...
Service /disk registered.
    => service_config <=
    => script_start:1,1 <=
    => script_waitchild <=
    => verbose <=
    => hostkeyb:0,0x60,1,12,2 <=
s0: map self 60000 -> 0 size 1000 offset 0 s 0 typed 1
s0: map self 64000 -> 0 size 1000 offset 0 s 0 typed 1
s0: map self 1ffd1000 -> 9dc00000 size 2000 offset 0 s 0 typed 2
s0: map self 1ffcf000 -> 9d800000 size 2000 offset 0 s 0 typed 2
sc: start 0-1 count 1
s0: map self 1ff80000 -> 9d400000 size 60000 offset 0 s 0 typed 2
s0: [ 5] module 'sigma0::mem:64 sigma0::dma name::/s0/log name::/s0/timer name::/s0/fs/rom name::/s0/admission name::/s0/disk ||' \
s0: ... ' rom:///apps/vancouver.nul PC_PS2 ||' \
s0: ... ' rom:///apps/hypervisor spinner ||' \
s0: ... ' rom:///apps/sigma0.nul S0_DEFAULT hostvga:0,0 hostkeyb hostserial:,,4, ||'
s0: map self 1bc00000 -> 99400000 size 4000000 offset 0 s 0 typed 9
s0: [ 5] using memory: 64 MB (4000000) at 1bc00000
s0: [ 5] creating PD with DMA on CPU 2
s0: [ 5, 4284e] pagefault 48/0 for 800061d7 err 4 at 800061d7
sc: wait for child 5
s0: [ 5, 4284e] 994061d7 99400000+4000000 -> order 22: 99400000+400000
s0: [ 5, 4284e] map 0/10 for 800061d7 err 4 at 800061d7
s0: [ 5, 4284e] pagefault 48/0 for bffff006 err 4 at 80000535
s0: [ 5, 4284e] 9d415006 9d415000+1000 -> order 12: 9d415000+1000
s0: [ 5, 4284e] map 0/1 for bffff006 err 4 at 80000535
tb: client data 3f000 guid 5 parent 925
(5) Ignored parameter: 'rom:///apps/vancouver.nul'
(5)     => PC_PS2 <=
(5)     => mem:0,0xa0000 <=
(5) physmem: 0 [0, a0000](5)     => mem:0x100000 <=
(5) physmem: 0 [100000, 3c00000](5)     => ioio <=
(5)     => nullio:0x80 <=
s0: => INIT done <
(5)     => pic:0x20,,0x4d0 <=
(5)     => pic:0xa0,2,0x4d1 <=
(5)     => pit:0x40,0 <=
(5)     => scp:0x92,0x61 <=
(5)     => kbc:0x60,1,12 <=
(5)     => keyb:0,0x10000 <=
(5)     => mouse:1,0x10001 <=
(5)     => rtc:0x70,8 <=
(5)     => serial:0x3f8,0x4,0x4711 <=
(5)     => hostsink:0x4712,80 <=
(5)     => vga:0x03c0 <=
(5) Allocating from guest 03be0000+20000
(5) VGA console 3be0000+20000 0x83fe0000
(5)     => vbios_disk <=
(5)     => vbios_keyboard <=
(5)     => hostkeyb:0x10,0x60,1,,1 <=
(5)     => vbios_mem <=
(5)     => vbios_time <=
(5)     => vbios_reset <=
(5)     => vbios_multiboot <=
(5)     => msi <=
(5)     => ioapic <=
(5)     => pcihostbridge:0,0x10,0xcf8,0xe0000000 <=
(5)     => pmtimer:0x8000 <=
(5)     => vcpus <=
(5)     => vcpu <=
(5)     create VCPU
(5)     => halifax <=
(5)     => vbios <=
(5)     => lapic <=
(5) startup
(5) LAPIC freq 174633750
(5) void DBus<M>::debug_dump() [with M = MessageHwIOIn]: Bus used 0 times.
(5)  0:     StaticReceiver<Y>::StaticReceiver() [with Y = IOAccess](5) 
(5) do_gsi_boot eip 80003485 esp 80238fec
(5) do_gsi_boot eip 80004824 esp 80237fec
(5) RESET device state
(5) INIT done
(5) reset CPU from 9 mtr_in e0010
(5) >   bool VirtualBiosMultiboot::receive(MessageBios&) rip ffff ilen 3 cr0 10 efl 10002
(5)     module 0 start 0x81c00000+10835 cmdline rom:///apps/hypervisor spinner
(5)     module 1 start 0x81c02000+640d8 cmdline rom:///apps/sigma0.nul S0_DEFAULT hostvg
(5) #   s0: => INIT done <=
(5) #  
s0: [ 6] module 'sigma0::mem:64 sigma0::dma name::/s0/log name::/s0/timer name::/s0/fs/rom name::/s0/admission name::/s0/disk ||' \
s0: ... ' rom:///apps/vancouver.nul PC_PS2 ahci drive:0,0,0 ||' \
s0: ... ' rom:///munich ||' \
s0: ... ' rom:///vmlinuz-3.4.4 clocksource=tsc root=/dev/ram0 ||' \
s0: ... ' rom:///initrd.gz sigma0::mem:64 sigma0::dma name::/s0/log name::/s0/timer name::/s0/fs/rom name::/s0/admission name::/s0/disk sigma0::drive:0 ||'
s0: map self 17c00000 -> 95400000 size 4000000 offset 0 s 0 typed 9
s0: [ 6] using memory: 64 MB (4000000) at 17c00000
s0: [ 6] creating PD with DMA on CPU 3
s0: [ 6, 4306e] pagefault 48/0 for 800061d7 err 4 at 800061d7
s0: [ 6, 4306e] 954061d7 95400000+4000000 -> order 22: 95400000+400000
s0: [ 6, 4306e] map 0/10 for 800061d7 err 4 at 800061d7
s0: [ 6, 4306e] pagefault 48/0 for bffff006 err 4 at 80000535
s0: [ 6, 4306e] 9d414006 9d414000+1000 -> order 12: 9d414000+1000
s0: [ 6, 4306e] map 0/1 for bffff006 err 4 at 80000535
tb: client data 3f002 guid 6 parent 928
(6) Ignored parameter: 'rom:///apps/vancouver.nul'
(6)     => PC_PS2 <=
(6)     => mem:0,0xa0000 <=
(6) physmem: 0 [0, a0000](6)     => mem:0x100000 <=
(6) physmem: 0 [100000, 3c00000](6)     => ioio <=
(6)     => nullio:0x80 <=
(6)     => pic:0x20,,0x4d0 <=
(6)     => pic:0xa0,2,0x4d1 <=
(6)     => pit:0x40,0 <=
(6)     => scp:0x92,0x61 <=
(6)     => kbc:0x60,1,12 <=
(6)     => keyb:0,0x10000 <=
(6)     => mouse:1,0x10001 <=
(6)     => rtc:0x70,8 <=
(6)     => serial:0x3f8,0x4,0x4711 <=
(6)     => hostsink:0x4712,80 <=
(6)     => vga:0x03c0 <=
(6) Allocating from guest 03be0000+20000
(6) VGA console 3be0000+20000 0x83fe0000
(6)     => vbios_disk <=
(6)     => vbios_keyboard <=
(6)     => hostkeyb:0x10,0x60,1,,1 <=
(6)     => vbios_mem <=
(6)     => vbios_time <=
(6)     => vbios_reset <=
(6)     => vbios_multiboot <=
(6)     => msi <=
(6)     => ioapic <=
(6)     => pcihostbridge:0,0x10,0xcf8,0xe0000000 <=
(6)     => pmtimer:0x8000 <=
(6)     => vcpus <=
(6)     => vcpu <=
(6)     create VCPU
(6)     => halifax <=
(6)     => vbios <=
(6) startup
(6)     => lapic <=
(6) LAPIC freq 174633750
(6)     => ahci <=
(6)     => drive:0,0,0 <=
(6) do_gsi_boot eip 80000e82 esp 80237fec
(6) __parameter_drive_function() line 421: '!mb.bus_disk.send(msg0) || msg0.error != MessageDisk::DISK_OK' error = 1 void __parameter_drive_function(Motherboard&, long unsigned int_, const char_, unsigne
(6) | d int) could not get disk 0 parameters error 0
(6) void DBus<M>::debug_dump() [with M = MessageHwIOIn]: Bus used 0 times.
(6)  0:     StaticReceiver<Y>::StaticReceiver() [with Y = IOAccess](6)
(6) do_gsi_boot eip 80003485 esp 80236fec
(6) do_gsi_boot eip 80004824 esp 80235fec
(6) RESET device state
(6) INIT done
(6) reset CPU from 9 mtr_in e0010
(6) >   bool VirtualBiosMultiboot::receive(MessageBios&) rip ffff ilen 3 cr0 10 efl 10002
(6)     module 0 start 0x81c00000+93c cmdline rom:///munich
(6)     module 1 start 0x81c02000+3e0c10 cmdline rom:///vmlinuz-3.4.4 clocksource=tsc roo
(6)     module 2 start 0x81fe4000+4e2000 cmdline rom:///initrd.gz
(6) sigma0::mem:64 sigma0::
(6) #   MUNICH: v.0.4.6 starts Linux
(6) #   MUNICH: 3.4.4 (ira@localhost.localdomain) #2 SMP Sun Jul 15 04:20:16 MSD 2012
(6) #   MUNICH: clocksource=tsc root=/dev/ram0
(6) #   MUNICH: initrd 1BE4000
(6) #   MUNICH: copy image
(6) #   MUNICH: start kernel
(6)     handle_int15 eax e801 ebx 0 ecx 0 edx 0 eip ffff efl 10002
(6)     handle_int15 eax c000 ebx 0 ecx 0 edx 0 eip ffff efl 10002
(6)     handle_int15 eax e980 ebx 0 ecx 0 edx 47534943 eip ffff efl 10002
(6)     handle_int15 eax 5300 ebx 0 ecx 0 edx 0 eip ffff efl 10002
(6) VESA 4f00 tag 0 base 40000+3940 esi 0
(6) bool AhciController::receive(MessageMem&)(1c) read failed
(6) bool AhciController::receive(MessageMem&)(20) read failed
(6) bool AhciController::receive(MessageMem&)(0) write failed
(6) bool AhciController::receive(MessageMem&)(c) write failed
(6) bool PS2Mouse::receive(MessagePS2&)(1, 88) unknown command
(6) bool PS2Mouse::receive(MessagePS2&)(1, 0) unknown command

**Comment by alex-ab** [comment]
Remove the stuff behind "rom:://initrd.gz ..." and add sigma0::drive:X to the first line of your vmlinux.nulconfig where X is the number of the disk as enumerated during sigma0 boot. Without "sigma0::drive" sigma0 disallows the VM to access the physical disc.

**Comment by sammmy** [comment]
I've changed my configuration file as you say but in this case I'm getting the following messages during the boot process:
...
(6) bool AhciController::receive(MessageMem&)(1c) read failed
(6) bool AhciController::receive(MessageMem&)(20) read failed
(6) not finished 1404034,0 inprogress 0
(6) not finished 1404034,0 inprogress 0
(6) bool AhciController::receive(MessageMem&)(0) write failed
(6) bool AhciController::receive(MessageMem&)(c) write failed
(6) not finished 1404034,0 inprogress 0
(6) not finished 1404034,0 inprogress 0
(6) IDENTIFY
(6) PIO setup fis
(6) push data 200 prdbase 37d5a80 _dsf 37d5a80 0 1
(6) IDENTIFY transfered
(6) bool PS2Mouse::receive(MessagePS2&)(1, 88) unknown command
(6) bool PS2Mouse::receive(MessagePS2&)(1, 0) unknown command
(6) not finished 1404034,0 inprogress 0
(6) not finished 1404034,0 inprogress 0
(6) IDENTIFY
(6) PIO setup fis
(6) push data 200 prdbase 37d5a80 _dsf 37d5a80 0 1
(6) IDENTIFY transfered
(6) not finished 1404034,0 inprogress 0
(6) not finished 1404034,0 inprogress 0
(6) IDENTIFY
(6) PIO setup fis
(6) push data 200 prdbase 37d5a80 _dsf 37d5a80 0 1
(6) IDENTIFY transfered
(6) not finished 1404034,0 inprogress 0
(6) not finished 1404034,0 inprogress 0

**Comment by wentasah** [comment]
For some reason, host drivers didn't detect any disk. My output looks like this:

```
    => vdisk:rom://diskbench.img <=
vdisk: Opened 'diskbench.img' 0x201 bytes.
vdisk: Attached as vdisk 0.
    => hostahci <=
s0: assign_pci(0xb80fa000, 0) failed: 8
MSI 7b enabled for bdf fa MSI fee00000/9b
DISK controller #1 AHCI fa id 1e028086 mmio f7d36000
AHCI: cap c730ff45 cap2 4 global 80000000 ports 1 version 10300 bohc 0
PORT 0 sig 101
_cl (0xbdfd7400,0xbdfd7800) _ct (0xb47e3c00, 0xb47ecc00)
 HDD ST250DM000-1BD141                        LBA48 sectors 1d1c5970
    => service_disk <=
disk: Added '0'
disk: Added '1'
Constructing service /disk...
Service /disk registered.
```

**Comment by vmmon** [comment]
> AHCI: cap e730ff45 cap2 4 global 80000000 ports 0 version 10300 bohc 0

The AHCI controller returns zero for the ports-implemented register.  Thus the BIOS or firmware, which has to initialize this register, thinks all of the 6 ports of the controller are unimplemented and not connected to a disk.

This is not a AHCI driver issue, but most likely a BIOS configuration problem.  Check whether you have enabled AHCI mode and disabled legacy mode for all controllers....

**Comment by blitz** [comment]
You may want to check whether there are specific workarounds for this controller in the Linux source.

**Comment by sammmy** [comment]
I've enabled AHCI Mode Control manually and have disabled legacy mode for controllers in BIOS configuration but it hasn't influenced on errors during the hard drive initialization process.
Thanks to all of you, I'll check the specific settings of controller.

**Comment by blitz** [comment]
Reopen this bug if there are new insights.
