### ISSUE TITLE
Unexpected DiskHelper behaviour

### ISSUE THREAD

**Issue by tfc** [TUD-OS/NUL#7]
Hi there,

I was very happy to find a handy utility like the Diskhelper, but it has one flaw:

It provides a 4KB disk_buffer by default, which you cannot use to full extent.
When doing a 

```
read_write_synch(true/false, disknum, start_sector, SIZE);
```

, SIZE has to be >= 512, but also <= 2KB (and SIZE & 0x1ff must not be != 0) [ according to hostahci.cc:158/318].

DiskHelper silently aborts if this rules are not followed, while the standard setting suggests that it is possible to use it with the 4KB buffer.

**Comment by alex-ab** [comment]
What do you mean by "silently"? Does read_write_sync doesn't return a error code (would be non equal to ENONE) ? The default disk_buffer size in DiskHelper is '4 << 20', so it should be usable to full extend. Can you provide a image or wv script to trigger the issue you observed ?

**Comment by blitz** [comment]
Please re-open if this is still an issue.
