### ISSUE TITLE
Capability allocation race in admission server

### ISSUE THREAD

**Issue by udosteinberg** [TUD-OS/NUL#8]
When using the following configuration...

```
exec    nova/hypervisor serial spinner iommu
load    vmm/sigma0.nul tracebuffer_verbose S0_DEFAULT hostvesa hostvga:0x40000,0x40000 hostkeyb:0,0x60,1,12,1 script_start:1,1,2
load    vmm/vancouver.nul
load    vmm/munich

load    linux/linux.nulconfig
load    linux/bzImage-3.6-32
load    linux/slackware-32.bz2
```

... in combination with enabling TRACE_REV and TRACE_ERROR in the hypervisor, the admission server dies when two instances of Linux are started in parallel (via script_start), because allocation of a semaphore capability fails. In particular, I have observed the following:

```
[ 0] REV OBJ PD:0xc1343160 B:0x000f0010 O:0x00 A:0x1f +
[ 2] REV OBJ PD:0xc1343160 B:0x000f000b O:0x00 A:0x1f +
[ 0] sys_create_sm: Non-NULL CAP (0xf000b) called from 0x80000106
```

CPU0 is revoking CAP f0010 concurrently with CPU2 revoking CAP f000b. Before CPU2 is done with its revoke operation on f000b, CPU0 is attempting to reallocate CAP f000b.

Inside the hypervisor the following sequence of events can be observed:

```
cpu:0 syscall:7 cap:0xf0010 begins
cpu:2 syscall:7 cap:0xf000b begins
cpu:0 syscall:7 cap:0xf0010 ends
cpu:0 syscall:6 cap:0xf000b begins
```

It is fairly obvious that CPU0 is doing its _create_sm_ hypercall before _revoke_ has returned on the other CPU. This is indicative of a capability allocator race in the admission server. As long as _revoke_ for a selector (range) has not returned, you can't reuse the selector(s).

**Comment by alex-ab** [comment]
Please give the patch a082df24f553894d0cf88ed763bff4ab1522cbbe a try.

**Comment by udosteinberg** [comment]
With the patch the problem is no longer reproducible. The old code that freed the selector before the revoke was done would very much explain the behavior I was seeing. So I think we can consider this fixed.

I assume you're going to make sure this fix hits upstream?

**Comment by alex-ab** [comment]
Ok. Yes, I will take care that it gets upstream. Thanks for the traces and reporting.
